"""Initial Helpdesk schema

Revision ID: cade080f4545
Revises: 
Create Date: 2026-08-08 23:47:00.469108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cade080f4545'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_is_active'), ['is_active'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)

    op.create_table('sla_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('resolution_hours', sa.Float(), nullable=False),
    sa.Column('warning_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('resolution_hours > 0', name='ck_positive_resolution_hours'),
    sa.CheckConstraint('warning_threshold_pct >= 0 AND warning_threshold_pct <= 100', name='ck_valid_threshold_pct'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_policies_priority'), ['priority'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('client', 'technician', 'admin', name='userrole'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('last_assigned_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_available'), ['is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('technician_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('proficiency >= 1 AND proficiency <= 5', name='ck_proficiency_range'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technician_id', 'skill_id', name='uq_technician_skill')
    )
    with op.batch_alter_table('technician_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technician_skills_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technician_skills_technician_id'), ['technician_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('Network', 'Hardware', 'Software', 'Access and Accounts', 'Email and Communication', 'Server and Infrastructure', name='ticketcategory'), nullable=True),
    sa.Column('priority', sa.Enum('Critical', 'High', 'Medium', 'Low', name='ticketpriority'), nullable=True),
    sa.Column('status', sa.Enum('New', 'Assigned', 'In Progress', 'Pending Client', 'Resolved', 'Closed', name='ticketstatus'), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('sla_state', sa.Enum('Healthy', 'Approaching Deadline', 'Breached', 'Completed', name='slastate'), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index('ix_tickets_assignee_status', ['assignee_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_sla_deadline'), ['sla_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_status'), ['status'], unique=False)
        batch_op.create_index('ix_tickets_status_sla', ['status', 'sla_state', 'sla_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_submitter_id'), ['submitter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_ticket_number'), ['ticket_number'], unique=True)

    op.create_table('classification_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('predicted_category', sa.String(length=50), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('category_model_version', sa.String(length=50), nullable=True),
    sa.Column('predicted_priority', sa.String(length=50), nullable=True),
    sa.Column('priority_confidence', sa.Float(), nullable=True),
    sa.Column('priority_model_version', sa.String(length=50), nullable=True),
    sa.Column('inference_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_category_overridden', sa.Boolean(), nullable=False),
    sa.Column('is_priority_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by_id', sa.Integer(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['overridden_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classification_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classification_predictions_ticket_id'), ['ticket_id'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_type', sa.Enum('ticket_assigned', 'sla_approaching', 'sla_breached', 'ticket_unassigned_alert', 'ticket_resolved', name='notificationtype'), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'skipped', name='notificationstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'classified', 'assigned', 'reassigned', 'category_overridden', 'priority_overridden', 'status_changed', 'sla_approaching', 'sla_breached', 'sla_completed', 'resolved', 'reopened', 'comment', name='eventtype'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_hash')
    )
    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_ticket_events_ticket_created', ['ticket_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_events_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_events_ticket_id'))
        batch_op.drop_index('ix_ticket_events_ticket_created')
        batch_op.drop_index(batch_op.f('ix_ticket_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_ticket_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_ticket_events_actor_id'))

    op.drop_table('ticket_events')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_idempotency_key'))

    op.drop_table('notifications')
    with op.batch_alter_table('classification_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classification_predictions_ticket_id'))

    op.drop_table('classification_predictions')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_tickets_submitter_id'))
        batch_op.drop_index('ix_tickets_status_sla')
        batch_op.drop_index(batch_op.f('ix_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_tickets_sla_deadline'))
        batch_op.drop_index(batch_op.f('ix_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_tickets_created_at'))
        batch_op.drop_index(batch_op.f('ix_tickets_category'))
        batch_op.drop_index('ix_tickets_assignee_status')
        batch_op.drop_index(batch_op.f('ix_tickets_assignee_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('technician_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technician_skills_technician_id'))
        batch_op.drop_index(batch_op.f('ix_technician_skills_skill_id'))

    op.drop_table('technician_skills')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_is_available'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sla_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_policies_priority'))

    op.drop_table('sla_policies')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_category'))

    op.drop_table('skills')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_is_active'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
