"""In-app notification model for admin-only alerting.

Stores persistent notifications in the DB. No SMTP/email is used.
Admins see a bell icon with unread count in the navbar.
"""

from datetime import datetime, timezone
from enum import Enum as PyEnum

from app.extensions import db


class NotificationType(PyEnum):
    """Types of notifications generated by the system."""
    TICKET_ASSIGNED          = 'ticket_assigned'
    SLA_APPROACHING          = 'sla_approaching'
    SLA_BREACHED             = 'sla_breached'
    TICKET_UNASSIGNED_ALERT  = 'ticket_unassigned_alert'
    TICKET_RESOLVED          = 'ticket_resolved'


class NotificationIcon(PyEnum):
    """Icon key used to render SVG/emoji in templates."""
    BELL       = 'bell'
    WARNING    = 'warning'
    DANGER     = 'danger'
    CHECK      = 'check'
    USER       = 'user'


class Notification(db.Model):
    """
    Persistent in-app notification record.

    Created by NotificationService whenever a significant system event occurs
    (SLA state change, ticket assignment, etc.).  The idempotency_key prevents
    duplicate records even if the trigger fires multiple times.
    """

    __tablename__ = 'notifications'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    notification_type = db.Column(
        db.Enum(NotificationType, values_callable=lambda x: [e.value for e in x]),
        nullable=False, index=True,
    )
    recipient_id = db.Column(
        db.Integer, db.ForeignKey('users.id'), nullable=False, index=True,
    )
    ticket_id = db.Column(
        db.Integer, db.ForeignKey('tickets.id'), nullable=True, index=True,
    )

    # Human-readable notification body shown in the bell dropdown / list page
    message = db.Column(db.Text, nullable=False, default='')

    # Icon key for template rendering
    icon = db.Column(
        db.String(32), nullable=False, default=NotificationIcon.BELL.value,
    )

    # Read state
    is_read = db.Column(db.Boolean, nullable=False, default=False, index=True)
    read_at = db.Column(db.DateTime, nullable=True)

    # Idempotency — prevents duplicate notifications for the same event
    idempotency_key = db.Column(
        db.String(255), nullable=False, unique=True, index=True,
    )

    created_at = db.Column(
        db.DateTime, nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    recipient = db.relationship('User', foreign_keys=[recipient_id])
    ticket    = db.relationship('Ticket', foreign_keys=[ticket_id])

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def mark_read(self):
        """Mark this notification as read."""
        if not self.is_read:
            self.is_read = True
            self.read_at = datetime.now(timezone.utc)

    @property
    def icon_enum(self):
        """Return the NotificationIcon enum value (for template use)."""
        try:
            return NotificationIcon(self.icon)
        except ValueError:
            return NotificationIcon.BELL

    def __repr__(self):
        return (
            f'<Notification {self.notification_type.value} '
            f'-> user {self.recipient_id} read={self.is_read}>'
        )
